<?php
// This file is never readable through HTTP when PHP is enabled.
if (!defined('ITEMS_MAIL_RELAY_CONFIG_LOAD')) {
    http_response_code(404);
    exit;
}
return [
    'secret' => '', // Generated by npm run setup:mail-relay. Same value as MAIL_RELAY_SECRET on Render.
    'smtpHost' => 'mail89.lwspanel.com', // LWS server name; alternative: mail.setup-hub.com.
    'smtpPort' => 465,
    'smtpSecure' => 'ssl', // 465: ssl; 587: tls.
    'smtpUser' => 'hello@setup-hub.com',
    'smtpPass' => '', // Enter the CURRENT mailbox password, only in relay-config.local.php on LWS.
    'fromEmail' => 'hello@setup-hub.com',
    'fromName' => 'ItemsTracker',
];
